#include <string>
#include <sstream>
using namespace std;
#include "text.h"

string CText::welcome_text()
{
	stringstream stream;
	stream << "\tWelcome to Mastermind! "
	       << "Are you ready for the game? Sure you are. =)" << endl;
	stream << "\nThis game is about all about code breaking. "
		   << "All you need to is break the code!" << endl;
	stream << "\nFor those who haven't, choose more info." << endl;
	stream << "\n\t(1) Play against computer."
		   << "\n\t(2) Play against another player."
		   << "\n\t(3) More info." 
		   << "\n\t(4) Exit game."<< endl;

	return stream.str();
}

string CText::info_text()
{
	stringstream stream;
	stream << "As I said before, this game is all about code breaking."
		   << "\nThere are 4 numbers that will be generated by computer(play against computer)"
		   << "\nor 4 numbers need to be inserted by each player(play against another player)."
		   << "\n\nThere are UNLIMITED number of TRIALS. You need to guess the correct number"
		   << "\nin the correct position as the original choosed or inserted number."
		   << "\nTHE NUMBERS MAY BE REPEATEd and ONLY NUMBER BETWEEN 1 TO 5 IS ALLOWED."
		   << "\n\nHow to understand the \"Results\": "
		   << "\n\t 1 = The number and the position is correct."
		   << "\n\t 2 = The number is wrong or not in the correct position." << endl;
		   //<< "\n\t 3 = This number is not in the code." << endl;

	return stream.str();
}

string CText::player_computer()
{
	stringstream stream;
	stream << "\n\tYou are playing against the computer!"
		   << "\nYou need to break the code choosed by the computer!" << endl;

	return stream.str();
}

string CText::player_player()
{
	stringstream stream;
	stream << "\n\tYour are playing against another player!"
		   << "\n\nFirst turns is Player 1 and after that is Player 2."
		   << "\nEach player need to insert 4 digits code as the initial code"
		   << "\nto be cracked. DO NOT LET YOUR OPPONENT SEE THE INITIAL CODE!" << endl;

	return stream.str();
}
