#include <string>
#include <sstream>
using namespace std;
#include "text.h"

string CText::welcome_text()
{
	stringstream stream;
	stream << "\tWelcome to Mastermind! "
	       << "Are you ready for the game? Sure you are. =)" << endl;
	stream << "All you need to do in this game is break the code!" << endl;
	stream << "\nFor those who haven't played before, choose more info. (3)" << endl;
	stream << "\n\t(1) Player 1 vs. Computer (Singleplayer mode)"
		   << "\n\t(2) Player 1 vs. Player 2 (Multiplayer mode)"
		   << "\n\t(3) More info about the game"
		   << "\n\t(4) Exit" << endl;

	return stream.str();
}

string CText::info_text()
{
	stringstream stream;
	stream << "As said before, this game is all about code breaking."
		   << "\nIn Singleplayer mode 4 numbers will be randomly generated by the computer."
		   << "\nIn Multiplayer mode 4 numbers need to be inserted by each player."
		   << "\n\nThere are UNLIMITED number of TRIALS. You need to guess the correct code"
		   << "\nin the order as generated or originally entered."
		   << "\nTHE NUMBERS MAY BE REPEATED and ONLY NUMBER BETWEEN 1 TO 5 IS ALLOWED."
		   << "\n\nHow to understand the \"Results\": "
		   << "\n\t 1 = The number and the position is correct."
		   << "\n\t 2 = The number is wrong or not in the correct position." << endl;

	return stream.str();
}

string CText::singleplayer()
{
	stringstream stream;
	stream << "\n\tYou are playing against the computer!"
		   << "\nYou need to break the code generated by the computer!" << endl;

	return stream.str();
}

string CText::multiplayer()
{
	stringstream stream;
	stream << "\n\tYou are playing against another player!"
		   << "\n\nFirst Player 1 inserts a code, then Player 2 enters a code"
		   << "\n and then they try and break each others codes."
		   << "\nThe code has to contain 4 numbers between 1 and 6."
		   << "\nDO NOT LET YOUR OPPONENT SEE THE INITIAL CODE!" << endl;

	return stream.str();
}
